
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>

//#include <concepts>
//#include <ranges>
//#include <numeric>


#include "ceto.h"


#include <ranges>
;
#include "macros_list_comprehension.donotedit.autogenerated.h"
;
    auto main() -> int {
        const auto l = [&]() {
                auto result { std::vector<std::ranges::range_value_t<decltype(std::ranges::iota_view(0, 10))>>() } ;
                for(const auto& x : std::ranges::iota_view(0, 10)) {
                    if ((x % 2) == 0) {
                        (*ceto::mad(result)).push_back(x);
                    }
                }
                return result;
                }();
        for(const auto& x : l) {
            std::cout << x;
        }
        const auto l2 = [&]() {
                auto result { std::vector<decltype(std::declval<std::ranges::range_value_t<decltype([&]() {
                        auto result { std::vector<std::ranges::range_value_t<decltype(std::ranges::iota_view(0, 10))>>() } ;
                        for(const auto& x : std::ranges::iota_view(0, 10)) {
                            if ((x % 2) == 0) {
                                (*ceto::mad(result)).push_back(x);
                            }
                        }
                        return result;
                        }())>>()+1)>() } ;
                for(const auto& x : l) {
                    (*ceto::mad(result)).push_back(x + 1);
                }
                return result;
                }();
        for(const auto& i : [&]() {
                auto result { std::vector<std::ranges::range_value_t<decltype([&]() {
                        auto result { std::vector<decltype(std::declval<std::ranges::range_value_t<decltype([&]() {
                                auto result { std::vector<std::ranges::range_value_t<decltype(std::ranges::iota_view(0, 10))>>() } ;
                                for(const auto& x : std::ranges::iota_view(0, 10)) {
                                    if ((x % 2) == 0) {
                                        (*ceto::mad(result)).push_back(x);
                                    }
                                }
                                return result;
                                }())>>()+1)>() } ;
                        for(const auto& x : l) {
                            (*ceto::mad(result)).push_back(x + 1);
                        }
                        return result;
                        }())>>() } ;
                for(const auto& x : l2) {
                    if (x > 5) {
                        (*ceto::mad(result)).push_back(x);
                    }
                }
                return result;
                }()) {
            std::cout << i;
        }
        for(const auto& i : [&]() {
                auto result { std::vector<decltype(std::declval<std::ranges::range_value_t<decltype([&]() {
                        auto result { std::vector<std::ranges::range_value_t<decltype(std::ranges::iota_view(0, 10))>>() } ;
                        for(const auto& x : std::ranges::iota_view(0, 10)) {
                            if ((x % 2) == 0) {
                                (*ceto::mad(result)).push_back(x);
                            }
                        }
                        return result;
                        }())>>()*100)>() } ;
                for(const auto& x : l) {
                    (*ceto::mad(result)).push_back(x * 100);
                }
                return result;
                }()) {
            std::cout << i;
        }
    }

