
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"


;

;

;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;

;
    auto main() -> int {
        auto a { "a" } ;
        std::cout << std::endl;
        std::cout << a << std::endl;
        std::cout << a << a << std::endl;
        std::cerr << "🙀" << a << a << std::endl;
        std::cerr << "🙀" << a << std::endl;
        std::cerr << "🙀" << a << std::endl;
        std::cout << std::endl;
        std::cerr << "🙀" << "aa\n";
        std::cerr << "🙀" << "aa\n\n";
        std::cerr << "🙀" << a << std::endl;
    }

