
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"
//#include "ceto_private_boundscheck.donotedit.autogenerated.h"

#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
    template <typename T1>
auto bad(const T1& a,  auto &  b) -> void {
        for(const auto& x : a) {
            (*ceto::mad(b)).push_back(1337);
        }
    }

    template <typename T1>
auto bad2(const T1& a,  auto &  b) -> void {
        const auto begin = (*ceto::mad(a)).cbegin();
        begin = unsafe([&]() -> decltype(auto) {
                static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(a)).cbegin()))>));
                return (*ceto::mad(a)).cbegin();
                }());
        const auto end = (*ceto::mad(a)).cend();
        (*ceto::mad(b)).clear();
        [&]() -> decltype(auto) {
                static_assert(!(std :: is_reference_v<decltype((std::cout << [&]() -> decltype(auto) {
                        static_assert(!(std :: is_reference_v<decltype((std::find(begin, end, 1)))>));
                        return std::find(begin, end, 1);
                        }()))>));
                return (std::cout << [&]() -> decltype(auto) {
                        static_assert(!(std :: is_reference_v<decltype((std::find(begin, end, 1)))>));
                        return std::find(begin, end, 1);
                        }());
                }() != end;
    }

struct Foo : public ceto::shared_object, public std::enable_shared_from_this<Foo> {

    decltype(std::vector {{1, 2, 3}}) a = std::vector {{1, 2, 3}};

        inline auto mm() -> void {
            ; // pass
        }

        inline auto bar() const -> void {
            ; // pass
        }

        inline auto foo() const -> void {
            const auto self = ceto::shared_from(this);
            const auto a = (this -> a);
            for(const auto& x : a) {
                std::cout << x;
                std::cout << "\n";
                this -> bar();
            }
            const auto l = [self = ceto::default_capture(self)]() {
                    if constexpr (!std::is_void_v<decltype((*ceto::mad(self)).bar())>) { return (*ceto::mad(self)).bar(); } else { static_cast<void>((*ceto::mad(self)).bar()); };
                    };
            const auto s = self;
            auto && b { (this -> a) } ;
            for(const auto& x : b) {
                std::cout << x;
                this -> bar();
                l();
                (*ceto::mad(s)).bar();
            }
            for(const auto& x : (this -> a)) {
                std::cout << x;
            }
        }

        inline auto foo() -> void {
            (*ceto::mad(this -> a)).push_back(4);
            std::cout << [&]() -> decltype(auto) {
                    static_assert(!(std :: is_reference_v<decltype(([&]() -> decltype(auto) {
                            static_assert(!(std :: is_reference_v<decltype((std::find([&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).begin()))>));
                                    return (*ceto::mad(this -> a)).begin();
                                    }(), [&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                                    return (*ceto::mad(this -> a)).end();
                                    }(), 1)))>));
                            return std::find([&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).begin()))>));
                                    return (*ceto::mad(this -> a)).begin();
                                    }(), [&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                                    return (*ceto::mad(this -> a)).end();
                                    }(), 1);
                            }() != [&]() -> decltype(auto) {
                            static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                            return (*ceto::mad(this -> a)).end();
                            }()))>));
                    return ([&]() -> decltype(auto) {
                            static_assert(!(std :: is_reference_v<decltype((std::find([&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).begin()))>));
                                    return (*ceto::mad(this -> a)).begin();
                                    }(), [&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                                    return (*ceto::mad(this -> a)).end();
                                    }(), 1)))>));
                            return std::find([&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).begin()))>));
                                    return (*ceto::mad(this -> a)).begin();
                                    }(), [&]() -> decltype(auto) {
                                    static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                                    return (*ceto::mad(this -> a)).end();
                                    }(), 1);
                            }() != [&]() -> decltype(auto) {
                            static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(this -> a)).end()))>));
                            return (*ceto::mad(this -> a)).end();
                            }());
                    }();
        }

};

struct Blah : public ceto::shared_object, public std::enable_shared_from_this<Blah> {

    std::shared_ptr<Foo> foo = std::make_shared<Foo>(); static_assert(ceto::is_non_aggregate_init_and_if_convertible_then_non_narrowing_v<decltype(std::make_shared<Foo>()), std::remove_cvref_t<decltype(foo)>>);

};

    auto main() -> int {
        const auto f = std::make_shared<const Foo>();
        (*ceto::mad(f)).foo();
        auto m { std::make_shared<Foo>() } ;
        (*ceto::mad(m)).foo();
        const auto ma = (*ceto::mad(m)).a;
        const auto element = ceto::bounds_check(ma, 3);
        std::cout << element;
        for(const auto& x : [&]() -> decltype(auto) {
                static_assert(!(std :: is_reference_v<decltype(((*ceto::mad(m)).a))>));
                return (*ceto::mad(m)).a;
                }()) {
            const auto ma2 = ma;
            std::cout << x;
        }
        auto ma3 { (*ceto::mad(m)).a } ;
        bad(ma3, ma3);
        const auto b = std::make_shared<const Blah>();
    }

