
#include "ceto.h"

;

;

;

;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;
#include <array>
;
    auto main() -> int {
        const auto a = std::array<int,3>{1, 2, 3};
        const std::array<int,3> a3 = {1, 2, 3};
        const std::array<int,3> a4 = std::array<int,3>{1, 2, 3}; static_assert(ceto::is_non_aggregate_init_and_if_convertible_then_non_narrowing_v<decltype(std::array<int,3>{1, 2, 3}), std::remove_cvref_t<decltype(a4)>>);
        const auto v = std::vector<int>{1, 2};
        const auto v2 = std::vector<int>(30, 5);
        const std::vector<int> v3 = {30, 5};
        for(const auto& x : {a, a3, a4}) {
            
    
                static_assert(requires { std::begin(x) + 2; }, "not a contiguous container");
                size_t ceto__private__size2 = std::size(x);
                for (size_t ceto__private__idx1 = 0; ; ceto__private__idx1++) {
                    if (std::size(x) != ceto__private__size2) {
                        std::cerr << "Container size changed during iteration: " << __FILE__ << " line: "<< __LINE__ << "\n";
                        std::terminate();
                    }
                    if (ceto__private__idx1 >= ceto__private__size2) {
                        break ;
                    }
                    const auto i = x[ceto__private__idx1];
                                    std::cout << i;

                }
            }
        for(const auto& x : {v, v2, v3}) {
            
    
                static_assert(requires { std::begin(x) + 2; }, "not a contiguous container");
                size_t ceto__private__size4 = std::size(x);
                for (size_t ceto__private__idx3 = 0; ; ceto__private__idx3++) {
                    if (std::size(x) != ceto__private__size4) {
                        std::cerr << "Container size changed during iteration: " << __FILE__ << " line: "<< __LINE__ << "\n";
                        std::terminate();
                    }
                    if (ceto__private__idx3 >= ceto__private__size4) {
                        break ;
                    }
                    const auto i = x[ceto__private__idx3];
                                    std::cout << i;

                }
            }
        ceto::safe_for_loop<!std::is_reference_v<decltype(std::array{a, a3, a4})> && ceto::OwningContainer<std::remove_cvref_t<decltype(std::array{a, a3, a4})>>>(std::array{a, a3, a4}, [&](auto &&ceto__private__lambda_param7) -> ceto::LoopControl {
    const auto x = ceto__private__lambda_param7;
            
    
                static_assert(requires { std::begin(x) + 2; }, "not a contiguous container");
                size_t ceto__private__size6 = std::size(x);
                for (size_t ceto__private__idx5 = 0; ; ceto__private__idx5++) {
                    if (std::size(x) != ceto__private__size6) {
                        std::cerr << "Container size changed during iteration: " << __FILE__ << " line: "<< __LINE__ << "\n";
                        std::terminate();
                    }
                    if (ceto__private__idx5 >= ceto__private__size6) {
                        break ;
                    }
                    const auto i = x[ceto__private__idx5];
                                    std::cout << i;

                }
    
    return ceto::LoopControl::Continue;
});        const auto get = [](const auto &t) -> void {
                (std::cout << ceto::bounds_check(std::get<0>(t), 0));
                };
        const auto t = std::tuple{a, a3, a4, v, v2, v3};
        const auto t2 = std::make_tuple(a, v);
        get(t);
        get(t2);
    }

