
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"


;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;
    template <typename T1>
auto list_size(const T1& lst) -> void {
        (((std::cout << "list size: ") << (*ceto::mad(lst)).size()) << " end") << std::endl;
        printf("add: %d", ((1 + 2) + 3) + 4);
    }

    auto main() -> int {
        list_size(std::vector {{1, 2, 3, 4}});
    }

