
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"


;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;
    auto main() -> int {
        const auto fp = fopen("file.txt", "w+");
        fprintf(fp, "hello %s", "world\n");
        fclose(fp);
        const auto fp2 = fopen("file.txt", "r");
        fclose(fp2);
        const auto t = std::ifstream("file.txt");
        auto buffer { std::stringstream() } ;
        buffer << (*ceto::mad(t)).rdbuf();
        const auto s = (*ceto::mad(buffer)).str();
        (std::cout << s) << "\n";
    }

