
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"
#include "ceto_checked_array_access.donotedit.autogenerated.h"

#include <iostream>
;
#include <cstdlib>
;

;
    auto main() -> int {
        (std::cout << 1) << "\n";
        (std::cout << (1 + 1)) << "\n";
        (std::cout << 1.5) << "\n";
        (std::cout << (1.500000l + 0.1)) << "\n";
    }

