
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"


;

;

;

;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;
struct Foo : public ceto::shared_object, public std::enable_shared_from_this<Foo> {

};

    auto main() -> int {
        if (ceto::make_shared_propagate_const<Foo>()) {
            std::cout << 5;
        }
        if (ceto::make_shared_propagate_const<Foo>()) {
            std::cout << 5;
        }
        if (ceto::make_shared_propagate_const<Foo>()) {
            std::cout << 5;
        }
    }

