
#include <string>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <cassert>
#include <compare> // for <=>
#include <thread>
#include <optional>


#include "ceto.h"


;

;

;

;

;

;

;

;

;

;

;

;

;

;
#include "ceto_private_listcomp.donotedit.autogenerated.h"
;
#include "ceto_private_boundscheck.donotedit.autogenerated.h"
;
#include "ceto_private_convenience.donotedit.autogenerated.h"
;
#include "ceto_private_append_to_pushback.donotedit.autogenerated.h"
;
struct Foo : public ceto::shared_object, public std::enable_shared_from_this<Foo> {

        ~Foo() {
            std::cout << "Foo destruct";
        }

};

    template <typename ceto__private__T21>
auto aliaser( auto &  f, const ceto__private__T21& g) -> void {
        std::cout << "in aliaser";
        f = nullptr;
        std::cout << (&g) -> use_count();
        std::cout << ((&g) -> get() == nullptr);
        std::cout << (g == nullptr);
    }

    auto main() -> int {
        auto f { ceto::make_shared_propagate_const<Foo>() } ;
        aliaser(f, f);
    }

